### ISSUE TITLE
Rails Dependency

### ISSUE THREAD

**Issue by cgriego** [FooBarWidget/encrypted_cookie_store#1]
Would love a version that worked for all Rack-based frameworks.

**Comment by FooBarWidget** [comment]
There's no standardized session store interface between frameworks, is there?

**Comment by cgriego** [comment]
Session storage is part of core Rack. It's the only session storage in Sinatra, for example. http://rack.rubyforge.org/doc/Rack/Session/Cookie.html

**Comment by FooBarWidget** [comment]
I have no plans to make this plugin framework-agnostic because I only use Rails to write web apps, but feel free to fork it.
