### ISSUE TITLE
Works Rails3?

### ISSUE THREAD

**Issue by plukevdh** [FooBarWidget/encrypted_cookie_store#2]
Any thought on whether or not this is Rails3 compatible? Any work being done to make it so?

**Comment by FooBarWidget** [comment]
It's probably not Rails 3 compatible. We're not using it ourselves anymore so we have no stake in maintaining it. If you want it to be Rails 3 compatible please feel free to submit a patch.

**Comment by twoism-dev** [comment]
There is now a Rails 3 version here: https://github.com/twoism-dev/encrypted_cookie_store

**Comment by FooBarWidget** [comment]
That looks good but it would be great if you can make it both Rails 2 and Rails 3 compatible.
